### ISSUE TITLE
Error: Unable to resolve module `./Interop`

### ISSUE THREAD

**Issue by Freddy03h** [reason-react-native/reason-react-navigation#38]
New issue since `5.0.1`
```
error: Error: Unable to resolve module `./Interop` from `node_modules/reason-react-navigation/src/Stack.bs.js`:
```
I think it's relative to this commit because I didn't get this issue on my branch : https://github.com/reason-react-native/reason-react-navigation/commit/64d12bbc898690a248fa5f15a215408c7e7516b9

**Comment by MoOx** [comment]
5.0.2 is out to fix this

**Comment by pedrobslisboa** [comment]
@MoOx I'm still with this issue at 5.1.3

![image](https://user-images.githubusercontent.com/35539594/121739758-6f0d0800-cad2-11eb-897e-ac32a36258f7.png)

**Comment by MoOx** [comment]
That's unexpected because file is actually available in the npm package https://unpkg.com/rescript-react-navigation@5.1.3/src/Interop.js
Can you investigate @pedrobslisboa ?

**Comment by Freddy03h** [comment]
It remind me some issue I've got before I configured `"in-source": true` in bsconfig

**Comment by jaredramirez** [comment]
We have a 100% rescript app, so we don't use `"in-source": true`. To get around this, we have have our scripts setup to run:
```bash
mkdir -p node_modules/rescript-react-navigation/lib/es6/src && cp node_modules/rescript-react-navigation/src/Interop.js node_modules/rescript-react-navigation/lib/es6/src/Interop.js
```
before every rescript build to make everything work.

Though, since `Interop` only exposes `identity`, I don't see why not just use the [type conversion escape hatch](https://rescript-lang.org/docs/manual/latest/type#type-escape-hatch).
